Lesson4
shcherbinaap/shop pull request #4
Opened 2020-12-13 15:54 UTC by shcherbinaap

Файлы 4 урока

2020-12-15 21:30 UTC, Vokler requested changes

2020-12-15 21:30 UTC, Vokler commented on mainapp/urls.py
> +	path('pk/', mainapp.products, name='product'),
Не совсем понял, почему тут просто передается pk? Тут должно быть название самого адреса - `products/`, а если хотите добавить pk, то так - `products/<int:pk>/`

2020-12-16 17:19 UTC, shcherbinaap commented on mainapp/urls.py
> +	path('pk/', mainapp.products, name='product'),
исправил, но если я правильно понимаю, то products/ идет в основном url, а в этом нужно было добавить <int:pk>/

2020-12-18 09:38 UTC, Vokler commented on mainapp/urls.py
> +	path('pk/', mainapp.products, name='product'),
Да, вы отчасти правы - в shop.urls идет глобальное название урла для папки mainapp, то есть по `products/`, а в mainapp.url идет уже обращение к определенному контроллеру, в данном случае mainapp.products - `product/`, и уже глубже - если перейти в какой-то определенный продукт, то `product/<int:id>/`.
То есть в shop.urls - должно быть `products/`, а в mainapp.url `product/<int:id>/`

2020-12-21 13:50 UTC, Vokler approved these changes

2020-12-21 13:51 UTC, merged